forum/urls.py
from django.conf.urls.defaults import *

urlpatterns = patterns('forum.views',
        (r'^pm/$', 'list_pms'),
        (r'^pm/(?P<post>\d+)/$', 'view_pm'),
        (r'^pm/(?P<post>\d+)/reply/$', 'reply_to_pm'),
        (r'^pm/(?P<post>\d+)/read/$', 'mark_pm_as_read'),
        (r'^pm/(?P<user>[-_a-zA-Z0-9]+)/$', 'start_pm'),
        (r'^signature/$', 'edit_sig'),

        (r'^$', 'view_forum'),
        (r'^(?P<forum>[-_a-z0-9]+)/$', 'view_forum'),
        (r'^(?P<forum>[-_a-z0-9]+)/post/$', 'post_topic'),
        (r'^(?P<forum>[-_a-z0-9]+)/(?P<post>\d+)/$', 'view_topic'),
        (r'^(?P<forum>[-_a-z0-9]+)/(?P<post>\d+)/reply/$', 'post_reply'),
        (r'^(?P<forum>[-_a-z0-9]+)/(?P<post>\d+)/edit/$', 'edit_topic'),
        (r'^(?P<forum>[-_a-z0-9]+)/(?P<post>\d+)/delete/$', 'delete_topic'),
        )

urls.py
from django.conf.urls.defaults import *

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
        (r'^(a|author)/', include('usermgmt.urls')),
        (r'^comments/', include('django.contrib.comments.urls')),
        (r'^(f|forums)/', include('forum.urls')),
        (r'^authors/$', 'usermgmt.views.all_authors'),
        (r'^interest/(?P<tag>[^/]+)/$', 'usermgmt.views.by_interest'),

        # user management
        (r'^accounts/login/$', 'django.contrib.auth.views.login'),
        (r'^accounts/logout/$', 'django.contrib.auth.views.logout_then_login'),
        (r'^accounts/register/$', 'usermgmt.account_views.create'),
        (r'^accounts/profile/$', 'usermgmt.account_views.show'),
        (r'^accounts/profile/update/$', 'usermgmt.account_views.update'),
        (r'^accounts/password/change/$', 'django.contrib.auth.views.password_change'),
        (r'^accounts/password/change/done/$', 'django.contrib.auth.views.password_change_done'),
        (r'^accounts/password/reset/$', 'django.contrib.auth.views.password_reset'),
        (r'^accounts/password/reset/confirm/(?P<uidb36>[0-9A-Za-z]+)-(?P<token>.+)/$', 'django.contrib.auth.views.password_reset_confirm'),
        (r'^accounts/password/reset/complete', 'django.contrib.auth.views.password_reset_complete'),
        (r'^accounts/password/reset/done/$', 'django.contrib.auth.views.password_reset_done'),

        (r'^admin/', include(admin.site.urls)),

        # everything else goes to ebooks
        ('^', include('ebook.urls')),
)

forum/models.py
from django.db import models
from django.contrib.auth.models import User

class ForumUser(models.Model):
    user = models.OneToOneField(User, primary_key = True)
    signature = models.TextField(blank = True)

class Forum(models.Model):
    slug = models.SlugField(primary_key = True)
    name = models.CharField(max_length = 120)
    description = models.CharField(max_length = 500)
    parent = models.ForeignKey('Forum', blank = True, null = True)
    moderators = models.ManyToManyField(User)
    users_can_post = models.BooleanField()

    def __unicode__(self):
        return self.name

    def get_absolute_url(self):
        if self.slug == '__root__':
            return '/forums/'
        else:
            return '/forums/%s/' % self.slug

class Post(models.Model):
    forum = models.ForeignKey('Forum')
    parent = models.ForeignKey('Post', blank = True, null = True)
    owner = models.ForeignKey(User)
    is_sticky = models.BooleanField()
    users_can_reply = models.BooleanField(default = True)
    title = models.CharField(max_length = 250)
    body = models.TextField()
    ctime = models.DateTimeField(auto_now_add = True)
    mtime = models.DateTimeField(auto_now = True)
    muser = models.ForeignKey(User, blank = True, null = True, related_name = 'modified_post')
    mreason = models.CharField(max_length = 250, blank = True, null = True)

    def __unicode__(self):
        return self.title

    class Meta:
        ordering = ['-is_sticky', 'ctime']

class PM(models.Model):
    user_to = models.ForeignKey(User, related_name = 'user_to')
    user_from = models.ForeignKey(User, related_name = 'user_from')
    parent = models.ForeignKey('PM', blank = True, null = True)
    title = models.CharField(max_length = 250)
    body = models.TextField()
    ctime = models.DateTimeField(auto_now_add = True)
    is_read = models.BooleanField()

    def __unicode__(self):
        return self.title

    def has_unread(self):
        to_ret = not self.is_read
        for p in self.pm_set.all():
            # check for unread PMs
            to_ret = to_ret or not p.is_read
        return to_ret

    class Meta:
        ordering = ['ctime']

forum/forms.py
from django import forms

class PostForm(forms.Form):
    title = forms.CharField(max_length = 250, required = False)
    body = forms.CharField(widget = forms.Textarea)

class PostEditForm(forms.Form):
    title = forms.CharField(max_length = 250, required = False)
    body = forms.CharField(widget = forms.Textarea)
    reason = forms.CharField(max_length = 250, required = False)

forum/views.py
from forum.models import *
from forum.forms import *
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, render_to_response
from django.template import RequestContext
from django.http import HttpResponseRedirect, Http404

def view_forum(request, forum = '__root__'):
    return render_to_response('forum/forum_detail.html', context_instance = RequestContext(request, {'forum': get_object_or_404(Forum, slug = forum), 'posts': Post.objects.filter(forum__slug__exact = forum).filter(parent__isnull = True)}))

def view_topic(request, forum, post):
    p = get_object_or_404(Post, id = post)
    if p.parent is not None:
        return HttpResponseRedirect('/forums/%s/%s/#%s%s' % (forum, p.parent.id, p.id, request.GET.get('minimal', None) is None and '' or '?minimal=true'))
    if not p.forum.slug == forum:
        request.user.message_set.create(message = "<span class=\"error\">I couldn't find that post in the forum requested; this is the only post with that ID!</span>")
        return HttpResponseRedirect('/forums/%s/%s/' % (p.forum.slug, p.id))
    return render_to_response(request.GET.get('minimal', None) is not None and 'forum/post_detail_minimal.html' or 'forum/post_detail.html', context_instance = RequestContext(request, {'post': p}))

@login_required
def post_topic(request, forum):
    f = get_object_or_404(Forum, slug = forum)
    if not f.users_can_post and not request.user in f.moderators:
        return render_to_response('forum/error.html', context_instance = RequestContext(request, {'error': "Users may not post to this forum"}))
    form = PostForm()
    if request.method == 'POST':
        form = PostForm(request.POST)
        if form.is_valid():
            p = Post(forum = f, owner = request.user, title = form.cleaned_data['title'], body = form.cleaned_data['body'])
            p.save()
            return HttpResponseRedirect('/forums/%s/%s/' % (forum, p.id))
    else:
        moderator = False
        if request.user in f.moderators.all():
            moderator = True
        return render_to_response('forum/post_form.html', context_instance = RequestContext(request, {'form': form, 'is_moderator': moderator}))

@login_required
def post_reply(request, forum, post):
    # get forum and parent post objects
    f = get_object_or_404(Forum, slug = forum)
    post_parent = get_object_or_404(Post, id = post)

    # make sure we can post
    if (not f.users_can_post or not post_parent.users_can_reply) and not request.user in f.moderators.all():
        return render_to_response('forum/error.html', context_instance = RequestContext(request, {'error': "Users may not post to this forum"}))

    # If the parent post is not the topic post, redirect to the reply-to-topic-post
    if post_parent.parent is not None:
        return HttpResponseRedirect('/forums/%s/%s/reply/?reply-to=%s' % (f.slug, parent.parent.id, parent.id))

    # Get our form - if data was POSTed, save it, and return to the post, otherwise, show the form with prepopulated fields
    form = PostForm()
    if request.method == 'POST':
        form = PostForm(request.POST)
        if form.is_valid():
            p = Post(forum = f, parent = post_parent, owner = request.user, title = form.cleaned_data['title'], body = form.cleaned_data['body'])
            p.save()
            return HttpResponseRedirect('/forums/%s/%s/' % (forum, p.id))
    else:
        if request.GET.get('reply-to', None):
            quote = get_object_or_404(Post, id = request.GET['reply-to'])
            form = PostForm(initial = {'title': 'Re: %s' % quote.title, 'body': '[quote=%s]\n%s\n[/quote]\n\n' % (quote.owner.first_name is not None and quote.owner.get_full_name() or quote.owner.username, quote.body)})
        else:
            form = PostForm(initial = {'title': 'Re: %s' % post_parent.title})
        return render_to_response('forum/post_reply_form.html', context_instance = RequestContext(request, {'form': form, 'topic_url': '/forums/%s/%s/?minimal=true#%s' % (forum, post, request.GET.get('reply-to', post))}))

@login_required
def edit_topic(request, forum, post):
    f = get_object_or_404(Forum, slug = forum)
    if not f.users_can_post and not (request.user in f.moderators.all()):
        return render_to_response('forum/error.html', context_instance = RequestContext(request, {'error': "Users may not post to this forum"}))
    p = get_object_or_404(Post, id = post)
    if not (request.user in f.moderators.all() or request.user == p.owner):
        return render_to_response('forum/error.html', context_instance = RequestContext(request, {'error': "Only the owner of a post or moderators may edit this post."}))
    form = PostEditForm({'title': p.title, 'body': p.body})
    if request.method == 'POST':
        form = PostEditForm(request.POST)
        if form.is_valid():
            p.title = form.cleaned_data['title']
            p.body = form.cleaned_data['body']
            p.mreason = form.cleaned_data['reason']
            p.muser = request.user
            p.save()
            return HttpResponseRedirect('/forums/%s/%s' % (forum, p.id))
    else:
        return render_to_response('forum/post_edit_form.html', context_instance = RequestContext(request, {'form': form}))

@login_required
def delete_topic(request, forum, post):
    p = get_object_or_404(Post, id = post)
    f = get_object_or_404(Forum, slug = forum)
    if not (request.user in f.moderators.all() or request.user == p.owner):
        return render_to_response('forum/error.html', context_instance = RequestContext(request, {'error': 'Only the owner of the post or moderators may delete this post.'}))
    if not p.parent:
        for child in p.post_set.all():
            child.delete()
        request.user.message_set.create(message = '<div class="success">Topic replies deleted</div>')
    p.delete()
    request.user.message_set.create(message = '<div class="success">Post deleted</div>')
    return HttpResponseRedirect('/forums/%s/' % forum)


@login_required
def list_pms(request):
    from django.db.models import Q
    pms = None
    try:
        pms = PM.objects.filter(Q(parent__exact = None), Q(user_to__exact = request.user) | Q(user_from__exact = request.user))
    except:
        pms = None
    return render_to_response('forum/list_pms.html', context_instance = RequestContext(request, {'pms': pms}))

@login_required
def view_pm(request, post):
    pm = get_object_or_404(PM, id = post)
    if (pm.user_to == request.user) or (pm.user_from == request.user):
        if pm.parent is not None:
            return HttpResponseRedirect('/forums/pm/%s/#%s' % (pm.parent.id, pm.id))
        return render_to_response(request.GET.get('minimal', None) is None and 'forum/pm_detail.html' or 'forum/pm_detail_minimal.html', context_instance = RequestContext(request, {'post': pm}))
    else:
        raise Http404()

@login_required
def mark_pm_as_read(request, post):
    pm = get_object_or_404(PM, id = post)
    if pm.user_to == request.user:
        pm.is_read = True
        pm.save()
        return HttpResponseRedirect('/forums/pm/%s' % post)
    else:
        raise Http404()

@login_required
def reply_to_pm(request, post):
    pm = get_object_or_404(PM, id = post)
    if (pm.user_to == request.user) or (pm.user_from == request.user):
        form = PostForm(initial = {'title': 'RE: %s' % pm.title, 'body': '[quote=%s]%s[/quote]' % (pm.user_from.username, pm.body)})
        if request.method == 'POST':
            form = PostForm(request.POST)
            if form.is_valid():
                newpm = PM(user_to = (pm.user_to == request.user and pm.user_from or request.user), 
                           user_from = request.user, parent = (pm.parent is None and pm or pm.parent), 
                           title = form.cleaned_data['title'], 
                           body = form.cleaned_data['body'],
                           is_read = False)
                newpm.save()
                return HttpResponseRedirect('/forums/pm/%s/' % (newpm.id))
        else:
            return render_to_response('forum/pm_reply_form.html', context_instance = RequestContext(request, {'pm': pm, 'form': form}))

    else:
        raise Http404

@login_required
def start_pm(request, user):
    u = get_object_or_404(User, username = user)
    form = PostForm()
    if request.method == 'POST':
        form = PostForm(request.POST)
        if form.is_valid():
            pm = PM(user_to = u, user_from = request.user, parent = None, title = form.cleaned_data['title'], body = form.cleaned_data['body'], is_read = False)
            pm.save()
            return HttpResponseRedirect('/forum/pm/%s/' % (pm.id))
    else:
        return render_to_response('forum/pm_post_form.html', context_instance = RequestContext(request, {'form': form, 'user_to': user}))

@login_required
def edit_sig(request):
    if not request.user.forumuser:
        f = ForumUser(user = request.user)
        f.save()
    if request.method == 'POST' and request.POST.get('signature', None) is not None:
        request.user.forumuser.signature = request.POST['signature']
        request.user.forumuser.save()
    return render_to_response('forum/edit_sig.html', context_instance = RequestContext(request, {'sig': ForumUser.objects.get(user = request.user).signature}))

templates/forum/base.html
{% extends "base.html" %}

{%block sectionheaders %}
<link rel="stylesheet" type="text/css" href="http://media.mjs-svc.com/manifesto/css/forum.css" />
<!--<ul>
    <li><a href="/forums/">Forum Home</a></li>
    {% if user.is_authenticated %}<li><a href="/forums/pm/">Private Messages</a></li>
    <li><a href="/forums/signature/">Edit Signature</a></li>{% endif %}
</ul>-->
{% endblock %}

templates/forum/base_minimal.html
<html>
    <head>
        <title>{% block title %}{% endblock %}</title>
    </head>
    <body>
        {% block content %}
        {% endblock %}
    </body>
</html>

templates/forum/edit_sig.html
{% extends "forum/base.html" %}

{% load bbcode %}

{% block title %}{% block header %}Edit user signature{% endblock %}{% endblock %}

{% block content %}
<form method="post">
    <table>
        <thead>
            <tr>
                <th><strong>Preview:</strong></th>
                <td><p>{{ user.forumuser.signature|striptags|bbcode|safe }}</p></td>
            </tr>
        </thead>
        <tbody>
            <tr>
                <th><label for="signature">Signature</label></th>
                <td><textarea name="signature" rows="10" cols="40">{{ sig }}</textarea></td>
            </tr>
            <tr>
                <th colspan="2"><input type="submit" value="Update signature" /></th>
            </tr>
        </tbody>
    </table>
</form>
{% endblock %}

templates/forum/forum_detail.html
{% extends "forum/base.html" %}

{% load bbcode %}
{% load forumtree %}

{% block title %}{% block header %}{{ forum.name }}{% endblock %}{% endblock %}

{% block content %}
{% if forum.parent %}{% ifnotequal forum.parent "__root__" %}
<p><a href="/forums/{{ forum.parent.slug }}/">&larr; Back to <em>{{ forum.parent.name }}</em></a></p>
{% endifnotequal %}{% endif %}
{% if forum.users_can_post %}
<p style="text-align: center"><form action="post/"><input type="submit" value="New Topic" /></form></p><br />
{% endif %}
<table id="forum">
    {% if posts %}
    <tr>
        <th>Post</th>
        <th width="15%">Replies</th>
    </tr>
    {% for post in posts %}
    <tr class="{% cycle "odd" "even" %}">
        <td><strong><a href="/forums/{{ post.forum.slug }}/{{ post.id }}/">{{ post.title }}</a></strong> -
            {% if post.owner.creator_set %}<a style="font-size: 75%" href="/store/creator/{{ post.owner.username }}/">{{ post.owner.get_full_name }}</a>
            {% else %}{{ post.owner.username }}{% endif %}<br />
            <p style="font-size: 75%">{{ post.body|striptags|stripbb|truncatewords_html:15|safe }}</p></td>
        <td class="pcount">{{ post.post_set.count }}</td>
    </tr>
    {% endfor %}
    {% if forum.forum_set.all %}
    <tr>
        <td colspan="2"><hr /></td>
    </tr>
    {% endif %}
    {% endif %}
    {% if forum.forum_set.all %}
    <tr>
        <th>Forum</th>
        <th width="15%">Post Count</th>
    </tr>
    {{ forum|forumtree }}
    {% endif %}
</table>
{% if forum.users_can_post %}
<p style="text-align: center"><form action="post/"><input type="submit" value="New Topic" /></form></p>
{% endif %}
{% endblock %}

templates/forum/list_pms.html
{% extends "forum/base.html" %}

{% load bbcode %}

{% block title %}{% block header %}Private Messages{% endblock %}{% endblock %}

{% block content %}
<table id="forum">
    <thead>
        <tr>
            <th>Private Message</th>
            <th>Posts</th>
        </tr>
    </thead>
    {% for pm in pms %}
    {% if pm.has_unread %}
    <tr class="unread">
    {% else %}
    <tr class="{% cycle "odd" "even" %}">
    {% endif %}
        <td><strong><a href="/forums/pm/{{ pm.id }}/">{{ pm.title }}</a></strong> -
            {% if pm.user_from.creator_set %}<a style="font-size: 75%" href="/store/creator/{{ pm.user_from.username }}/">{{ pm.user_from.get_full_name }}</a>
            {% else %}{{ pm.user_from.username }}{% endif %} &rarr;
            {% if pm.user_to.creator_set %}<a style="font-size: 75%" href="/store/creator/{{ pm.user_to.username }}/">{{ pm.user_to.get_full_name }}</a>
            {% else %}{{ pm.user_to.username }}{% endif %}<br />
            <p style="font-size: 75%">{{ pm.body|striptags|truncatewords:25|bbcode|safe }}</p></td>
        <td>{{ pm.pm_set.count }}</td>
    </tr>
    {% endfor %}
</table>
{% endblock %}

templates/forum/pm_detail.html
{% extends "forum/base.html" %}

{% load bbcode %}

{% block title %}{% block header %}{{ post.title }}{% endblock %}{% endblock %}

{% block content %}
<table id="forum">
    <thead>
        <tr>
            <th width="25%">Users</th>
            <th>Private Message</th>
        </tr>
    </thead>
    <tbody>
        <tr class="odd">
            <td><div class="forum-poster"><a name="{{ post.id }}"> </a><strong>From:
                {% ifequal post.user_from user %}you{% else %}
                {% if post.user_from.creator_set %}<a href="/store/creator/{{ post.user_from.username }}/">{{ post.user_from.get_full_name }}</a>
                {% else %}{{ post.user_from.username }}{% endif %}
                {% endifequal %}<br /> To:
                {% ifequal post.user_to user %}you{% else %}
                {% if post.user_to.creator_set %}<a href="/store/creator/{{ post.user_to.username }}/">{{ post.user_to.get_full_name }}</a>
                {% else %}{{ post.user_to.username }}{% endif %}
                {% endifequal %}
            </strong></div></td>
            <td><div class="post-header"><strong>{{ post.title }}</strong></div><div class="post-controls">[ 
                <a href="/forums/pm/{{ post.id }}/reply?reply-to={{ p.id }}">Quote</a> 
                {% ifequal post.user_to user %}{% if not post.is_read %}| <a href="/forums/pm/{{ post.id }}/read"><strong>Mark as read</strong></a>{% endif %}{% endifequal %}
                ]</div>
                <div class="post-body">{{ post.body|striptags|bbcode|safe }}</div></td>
        </tr>
        {% for p in post.pm_set.all %}
        <tr class="{% cycle "even" "odd" %}">
            <td><div class="forum-poster"><a name="{{ p.id }}"> </a><strong>From:
                {% ifequal p.user_from user %}you{% else %}
                {% if p.user_from.creator_set %}<a href="/store/creator/{{ p.user_from.username }}/">{{ p.user_from.get_full_name }}</a>
                {% else %}{{ p.user_from.username }}{% endif %}
                {% endifequal %}<br /> To:
                {% ifequal p.user_to user %}you{% else %}
                {% if p.user_to.creator_set %}<a href="/store/creator/{{ p.user_to.username }}/">{{ p.user_to.get_full_name }}</a>
                {% else %}{{ p.user_to.username }}{% endif %}
                {% endifequal %}
            </strong></div></td>
            <td><div class="post-header"><abbr text="In reply to {{ post.title }}">{{ p.title }}</abbr></div><div class="post-controls">[ 
                <a href="/forums/pm/{{ post.id }}/reply?reply-to={{ p.id }}">Quote</a> 
                {% ifequal p.user_to user %}{% if not p.is_read %}| <a href="/forums/pm/{{ p.id }}/read"><strong>Mark as read</strong></a>{% endif %}{% endifequal %}
                ]</div>
                <div class="post-body">{{ p.body|striptags|bbcode|safe }}</div></td>
        </tr>
        {% endfor %}
    </tbody>
    <tfoot>
        <tr>
            <th colspan="2">
                <form action="/forums/pm/{{ post.id }}/reply/">
                    <input type="submit" value="Reply" />
                </form>
            </th>
        </tr>
    </tfoot>
</table>
{% endblock %}

templates/forum/pm_detail_minimal.html
{% extends "forum/base_minimal.html" %}

{% load bbcode %}

{% block title %}{% block header %}{{ post.title }}{% endblock %}{% endblock %}

{% block content %}
<table id="forum">
    <thead>
        <tr>
            <th width="25%">User</th>
            <th>Private Message</th>
        </tr>
    </thead>
    <tbody>
        <tr class="odd">
            <td><div class="forum-poster"><a name="{{ post.id }}"><strong>
                {% if post.owner.creator_set %}<a href="/store/creator/{{ post.owner.username }}/">{{ post.owner.get_full_name }}</a>
                {% else %}{{ post.owner.username }}{% endif %}
            </strong></a></div></td>
            <td><div class="post-header"><strong>{{ post.title }}</strong></div>
                <div class="post-body">{{ post.body|striptags|bbcode|safe }}</div></td>
        </tr>
        {% for p in post.post_set.all %}
        <tr class="{% cycle "even" "odd" %}">
            <td><div class="forum-poster"><a name="{{ p.id }}"><strong>
                {% if p.owner.creator_set %}<a href="/store/creator/{{ p.owner.username }}/">{{ p.owner.get_full_name }}</a>
                {% else %}{{ p.owner.username }}{% endif %}
            </strong></a></div></td>
            <td><div class="post-header"><abbr text="In reply to {{ post.title }}">{{ p.title }}</abbr></div>
                <div class="post-body">{{ p.body|striptags|bbcode|safe }}</div></td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}

templates/forum/pm_post_form.html
{% extends "base.html" %}

{% block title %}{% block header %}New Private Message{% endblock %}{% endblock %}

{% block content %}
<form method="post">
<table width="100%">
    <thead>
        <tr>
            <th colspan="2">Private message to {{ user_to }}</th>
    <tbody>
        <tr>
            <th width="25%"><label for="title">Title</label></th>
            <td>{{ form.title }}</td>
        </tr>
        <tr>
            <th><label for="body">Body</label></th>
            <td>{{ form.body }}</td>
        </tr>
    </tbody>
    <tfoot>
        <tr>
            <th colspan="2">
                <input type="submit" value="Send PM" />
            </th>
        </tr>
    </tfoot>
</table>
</form>
{% endblock %}

templates/forum/pm_reply_form.html
{% extends "forum/base.html" %}

{% block title %}{% block header %}{% endblock %}{% endblock %}

{% block content %}
<form method="post">
<table width="100%">
    <thead>
        <tr>
            <th colspan="2">
                <iframe width="80%" height="200px" src="/forums/pm/{{ pm.id }}?minimal=true"></iframe>
            </th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <th width="25%"><label for="title">Title</label></th>
            <td>{{ form.title }}</td>
        </tr>
        <tr>
            <th><label for="body">Body</label></th>
            <td>{{ form.body }}</td>
        </tr>
    </tbody>
    <tfoot>
        <tr>
            <th colspan="2">
                <input type="submit" value="Submit reply" />
            </th>
        </tr>
    </tfoot>
</table>
</form>
{% endblock %}

templates/forum/post_detail_minimal.html
{% extends "forum/base_minimal.html" %}

{% load bbcode %}

{% block title %}{% block header %}{{ post.title }}{% endblock %}{% endblock %}

{% block content %}
<table id="forum" style="width: 100%">
    <thead>
        <tr>
            <th width="20%">User</th>
            <th>Post</th>
        </tr>
    </thead>
    <tbody>
        <tr class="odd">
            <td><div class="forum-poster"><a name="{{ post.id }}"><strong>
                {% if post.owner.creator_set %}<a href="/store/creator/{{ post.owner.username }}/">{{ post.owner.get_full_name }}</a>
                {% else %}{{ post.owner.username }}{% endif %}
            </strong></a></div></td>
            <td><div class="post-header"><strong>{{ post.title }}</strong></div>
                <div class="post-body">{{ post.body|striptags|bbcode|safe }}</div></td>
        </tr>
        {% for p in post.post_set.all %}
        <tr class="{% cycle "even" "odd" %}">
            <td><div class="forum-poster"><a name="{{ p.id }}"><strong>
                {% if p.owner.creator_set %}<a href="/store/creator/{{ p.owner.username }}/">{{ p.owner.get_full_name }}</a>
                {% else %}{{ p.owner.username }}{% endif %}
            </strong></a></div></td>
            <td><div class="post-header"><abbr text="In reply to {{ post.title }}">{{ p.title }}</abbr></div>
                <div class="post-body">{{ p.body|striptags|bbcode|safe }}</div></td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}

templates/forum/post_edit_form.html
{% extends "forum/base.html" %}

{% block title %}{% block header %}Edit post {{ post.title }}{% endblock %}{% endblock %}

{% block content %}
<form method="post">
<table width="100%">
    <tbody>
        <tr>
            <th width="25%"><label for="title">Title</label></th>
            <td>{{ form.title }}</td>
        </tr>
        <tr>
            <th><label for="body">Body</label></th>
            <td>{{ form.body }}</td>
        </tr>
        <tr>
            <th><label for="reason">Reason for edit:</label></th>
            <td>{{ form.reason }}</td>
        </tr>
    </tbody>
    <tfoot>
        <tr>
            <th colspan="2">
                <input type="submit" value="Submit reply" />
            </th>
        </tr>
    </tfoot>
</table>
</form>

{% endblock %}

templates/forum/post_form.html
{% extends "forum/base.html" %}

{% block title %}{% block header %}{% endblock %}{% endblock %}

{% block content %}
<form method="post">
<table width="100%">
    <tbody>
        <tr>
            <th width="25%"><label for="title">Title</label></th>
            <td>{{ form.title }}</td>
        </tr>
        <tr>
            <th><label for="body">Body</label><br />BBCode enabled; HTML disabled</th>
            <td>{{ form.body }}</td>
        </tr>
    </tbody>
    <tfoot>
        <tr>
            <th colspan="2">
                <input type="submit" value="Submit reply" />
            </th>
        </tr>
    </tfoot>
</table>
</form>
{% endblock %}